travis:
  secure:
    BINSTAR_TOKEN: oEcn59yN8K94dCX0YjJSQfei2Xy4CVXKcytqhEssvJVXmXIOdOLNsMtYHLGqYiPT83aRBggKAmD3G8IFnpoxyB6RNJLlZgUyDbW0wF70nPvD5tCAh4p/uN1yprpFgAFLsRN/2IlA/n/WQhlPYE0J5e7WI3DZzkWLXLs+8uM0HgnELXDm7tgemoNGWgHp5FTdzAZunM0Wm9pKqt5t0MxNZoLrneTUgstQaCpglv0eXBZ9AlCzLV3Ukg6Sqp08t7vaM4X9jhaJ+XA5+tBCIk56sy3tave+98ZJrtWykAeUAzAsEFq6qC4sZdySo5ONPY0X5pFIUEMpr03uUHbARnHY7rQJKITZNIkSUR3Y+SKiUPu+9ETrc7D5Z5PnmDGyxRjxy7/veD15O7ttPkVKgypMkdN9KjGVzrP1i3Cixl649ZPiJBm25vqBb7NTCTSURmPlFhMJ+7BdfLB5/y47ZWESPAOEWwUc3jM7evofT1HLHeD55k4zUP+HIyUOD95K/Dy5vfzkxnrJSS38u1DaqDjfkMEwuVZmXdK8D6vR2rzSLB15S/pemRX+xxGrdx+J5Y96jYdeMV/nKJ3Hl9MJ/H60dNwAO1bSxFiwmxlCpw0Zj+mN3U7Fc71XQUQFhOy0iRgeM85XKcsNZZPoUOenYgX3Sr4DrH5xMjlBHsaJrbr0wsI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
